=begin
#Fortnox Swagger

#Fortnox API Swagger

OpenAPI spec version: 3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for StandoutFortnox::EmployeesApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'EmployeesApi' do
  before do
    # run before each test
    @instance = StandoutFortnox::EmployeesApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of EmployeesApi' do
    it 'should create an instance of EmployeesApi' do
      expect(@instance).to be_instance_of(StandoutFortnox::EmployeesApi)
    end
  end

  # unit tests for add_employee
  # Create employee
  # Create customer
  # @param body Employee object to create
  # @param [Hash] opts the optional parameters
  # @return [Employee]
  describe 'add_employee test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  # unit tests for update_employee
  # Update employee
  # @param employee_id Numeric id of the employee
  # @param body Employee object to update
  # @param [Hash] opts the optional parameters
  # @return [Employee]
  describe 'update_employee test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
