=begin
#Fortnox Swagger

#Fortnox API Swagger

OpenAPI spec version: 1.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'

# Unit tests for StandoutFortnox::VouchersApi
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'VouchersApi' do
  before do
    # run before each test
    @instance = StandoutFortnox::VouchersApi.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of VouchersApi' do
    it 'should create an instance of VouchersApi' do
      expect(@instance).to be_instance_of(StandoutFortnox::VouchersApi)
    end
  end

  # unit tests for add_voucher
  # Create a voucher
  # The created voucher will be returned if everything succeeded, if there was any problems an error will be returned.
  # @param body Voucher object to create
  # @param [Hash] opts the optional parameters
  # @return [Voucher]
  describe 'add_voucher test' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
