=begin
#Fortnox Swagger

#Fortnox API Swagger

OpenAPI spec version: 1.0.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.12

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for SwaggerClient::Invoice2
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Invoice2' do
  before do
    # run before each test
    @instance = SwaggerClient::Invoice2.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Invoice2' do
    it 'should create an instance of Invoice2' do
      expect(@instance).to be_instance_of(SwaggerClient::Invoice2)
    end
  end
  describe 'test attribute "invoice"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
