=begin
#Fortnox Swagger

#Fortnox API Swagger

OpenAPI spec version: 1.0.1

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'spec_helper'
require 'json'
require 'date'

# Unit tests for StandoutFortnox::Offers
# Automatically generated by swagger-codegen (github.com/swagger-api/swagger-codegen)
# Please update as you see appropriate
describe 'Offers' do
  before do
    # run before each test
    @instance = StandoutFortnox::Offers.new
  end

  after do
    # run after each test
  end

  describe 'test an instance of Offers' do
    it 'should create an instance of Offers' do
      expect(@instance).to be_instance_of(StandoutFortnox::Offers)
    end
  end
  describe 'test attribute "offers"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

  describe 'test attribute "meta_information"' do
    it 'should work' do
      # assertion here. ref: https://www.relishapp.com/rspec/rspec-expectations/docs/built-in-matchers
    end
  end

end
