=begin
#Fortnox Swagger

#Fortnox API Swagger

OpenAPI spec version: 3

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 3.0.23
=end

require 'date'

module StandoutFortnox
  class InvoicesInvoices
    # Direct url to the record.
    attr_accessor :url

    # Balance of the invoice.
    attr_accessor :balance

    # If the invoice is bookkept. This value can be changed by using the action 'bookkeep'.
    attr_accessor :booked

    # If the invoice is cancelled. This value can be changed by using the action 'cancel'.
    attr_accessor :cancelled

    # Code of the cost center. The code must be of an existing cost center.
    attr_accessor :cost_center

    # Code of the currency. The code must be of an existing currency.
    attr_accessor :currency

    # Currency rate used for the invoice.
    attr_accessor :currency_rate

    # Currency unit used for the invoice.
    attr_accessor :currency_unit

    # Name of the customer.
    attr_accessor :customer_name

    # Customer number of the customer. The customer number must be of an existing customer.
    attr_accessor :customer_number

    # The invoice number. If no document number is provided, the next number in the series will be used.
    attr_accessor :document_number

    # Due date of the invoice. Must be a valid date according to our date format.
    attr_accessor :due_date

    # External invoice reference 1.
    attr_accessor :external_invoice_reference1

    # External invoice reference 2.
    attr_accessor :external_invoice_reference2

    # Invoice date. Must be a valid date according to our date format.
    attr_accessor :invoice_date

    # The type of invoice. Can be INVOICE AGREEMENTINVOICE INTRESTINVOICE SUMMARYINVOICE or CASHINVOICE.
    attr_accessor :invoice_type

    # If the invoice is managed by NoxFinans
    attr_accessor :nox_finans

    # OCR number of the invoice.
    attr_accessor :ocr

    # Code of the project. The code must be of an existing project.
    attr_accessor :project

    # If the document is printed or sent in any way.
    attr_accessor :sent

    # Code of the terms of payment. The code must be of an existing terms of payment.
    attr_accessor :terms_of_payment

    # The total amount of the invoice.
    attr_accessor :total

    # Code of the way of delivery. The code must be of an existing way of delivery.
    attr_accessor :way_of_delivery

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'url' => :'@url',
        :'balance' => :'Balance',
        :'booked' => :'Booked',
        :'cancelled' => :'Cancelled',
        :'cost_center' => :'CostCenter',
        :'currency' => :'Currency',
        :'currency_rate' => :'CurrencyRate',
        :'currency_unit' => :'CurrencyUnit',
        :'customer_name' => :'CustomerName',
        :'customer_number' => :'CustomerNumber',
        :'document_number' => :'DocumentNumber',
        :'due_date' => :'DueDate',
        :'external_invoice_reference1' => :'ExternalInvoiceReference1',
        :'external_invoice_reference2' => :'ExternalInvoiceReference2',
        :'invoice_date' => :'InvoiceDate',
        :'invoice_type' => :'InvoiceType',
        :'nox_finans' => :'NoxFinans',
        :'ocr' => :'OCR',
        :'project' => :'Project',
        :'sent' => :'Sent',
        :'terms_of_payment' => :'TermsOfPayment',
        :'total' => :'Total',
        :'way_of_delivery' => :'WayOfDelivery'
      }
    end

    # Attribute type mapping.
    def self.openapi_types
      {
        :'url' => :'Object',
        :'balance' => :'Object',
        :'booked' => :'Object',
        :'cancelled' => :'Object',
        :'cost_center' => :'Object',
        :'currency' => :'Object',
        :'currency_rate' => :'Object',
        :'currency_unit' => :'Object',
        :'customer_name' => :'Object',
        :'customer_number' => :'Object',
        :'document_number' => :'Object',
        :'due_date' => :'Object',
        :'external_invoice_reference1' => :'Object',
        :'external_invoice_reference2' => :'Object',
        :'invoice_date' => :'Object',
        :'invoice_type' => :'Object',
        :'nox_finans' => :'Object',
        :'ocr' => :'Object',
        :'project' => :'Object',
        :'sent' => :'Object',
        :'terms_of_payment' => :'Object',
        :'total' => :'Object',
        :'way_of_delivery' => :'Object'
      }
    end

    # List of attributes with nullable: true
    def self.openapi_nullable
      Set.new([
      ])
    end
  
    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      if (!attributes.is_a?(Hash))
        fail ArgumentError, "The input argument (attributes) must be a hash in `StandoutFortnox::InvoicesInvoices` initialize method"
      end

      # check to see if the attribute exists and convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h|
        if (!self.class.attribute_map.key?(k.to_sym))
          fail ArgumentError, "`#{k}` is not a valid attribute in `StandoutFortnox::InvoicesInvoices`. Please check the name to make sure it's valid. List of attributes: " + self.class.attribute_map.keys.inspect
        end
        h[k.to_sym] = v
      }

      if attributes.key?(:'url')
        self.url = attributes[:'url']
      end

      if attributes.key?(:'balance')
        self.balance = attributes[:'balance']
      end

      if attributes.key?(:'booked')
        self.booked = attributes[:'booked']
      end

      if attributes.key?(:'cancelled')
        self.cancelled = attributes[:'cancelled']
      end

      if attributes.key?(:'cost_center')
        self.cost_center = attributes[:'cost_center']
      end

      if attributes.key?(:'currency')
        self.currency = attributes[:'currency']
      end

      if attributes.key?(:'currency_rate')
        self.currency_rate = attributes[:'currency_rate']
      end

      if attributes.key?(:'currency_unit')
        self.currency_unit = attributes[:'currency_unit']
      end

      if attributes.key?(:'customer_name')
        self.customer_name = attributes[:'customer_name']
      end

      if attributes.key?(:'customer_number')
        self.customer_number = attributes[:'customer_number']
      end

      if attributes.key?(:'document_number')
        self.document_number = attributes[:'document_number']
      end

      if attributes.key?(:'due_date')
        self.due_date = attributes[:'due_date']
      end

      if attributes.key?(:'external_invoice_reference1')
        self.external_invoice_reference1 = attributes[:'external_invoice_reference1']
      end

      if attributes.key?(:'external_invoice_reference2')
        self.external_invoice_reference2 = attributes[:'external_invoice_reference2']
      end

      if attributes.key?(:'invoice_date')
        self.invoice_date = attributes[:'invoice_date']
      end

      if attributes.key?(:'invoice_type')
        self.invoice_type = attributes[:'invoice_type']
      end

      if attributes.key?(:'nox_finans')
        self.nox_finans = attributes[:'nox_finans']
      end

      if attributes.key?(:'ocr')
        self.ocr = attributes[:'ocr']
      end

      if attributes.key?(:'project')
        self.project = attributes[:'project']
      end

      if attributes.key?(:'sent')
        self.sent = attributes[:'sent']
      end

      if attributes.key?(:'terms_of_payment')
        self.terms_of_payment = attributes[:'terms_of_payment']
      end

      if attributes.key?(:'total')
        self.total = attributes[:'total']
      end

      if attributes.key?(:'way_of_delivery')
        self.way_of_delivery = attributes[:'way_of_delivery']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          url == o.url &&
          balance == o.balance &&
          booked == o.booked &&
          cancelled == o.cancelled &&
          cost_center == o.cost_center &&
          currency == o.currency &&
          currency_rate == o.currency_rate &&
          currency_unit == o.currency_unit &&
          customer_name == o.customer_name &&
          customer_number == o.customer_number &&
          document_number == o.document_number &&
          due_date == o.due_date &&
          external_invoice_reference1 == o.external_invoice_reference1 &&
          external_invoice_reference2 == o.external_invoice_reference2 &&
          invoice_date == o.invoice_date &&
          invoice_type == o.invoice_type &&
          nox_finans == o.nox_finans &&
          ocr == o.ocr &&
          project == o.project &&
          sent == o.sent &&
          terms_of_payment == o.terms_of_payment &&
          total == o.total &&
          way_of_delivery == o.way_of_delivery
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Integer] Hash code
    def hash
      [url, balance, booked, cancelled, cost_center, currency, currency_rate, currency_unit, customer_name, customer_number, document_number, due_date, external_invoice_reference1, external_invoice_reference2, invoice_date, invoice_type, nox_finans, ocr, project, sent, terms_of_payment, total, way_of_delivery].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def self.build_from_hash(attributes)
      new.build_from_hash(attributes)
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.openapi_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        elsif attributes[self.class.attribute_map[key]].nil? && self.class.openapi_nullable.include?(key)
          self.send("#{key}=", nil)
        end
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :Boolean
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        StandoutFortnox.const_get(type).build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        if value.nil?
          is_nullable = self.class.openapi_nullable.include?(attr)
          next if !is_nullable || (is_nullable && !instance_variable_defined?(:"@#{attr}"))
        end

        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end  end
end
