=begin
#Fortnox Swagger

#Fortnox API Swagger

OpenAPI spec version: 1.1.0

Generated by: https://github.com/swagger-api/swagger-codegen.git
Swagger Codegen version: 2.4.14

=end

require 'date'

module StandoutFortnox
  # The properties for this object is listed in the table for 'EDI Information'.
  class InvoiceInvoiceEDIInformation
    # Invoice address GLN for EDI
    attr_accessor :edi_global_location_number

    # Delivery address GLN for EDI
    attr_accessor :edi_global_location_number_delivery

    # Extra EDI Information
    attr_accessor :edi_invoice_extra1

    # Extra EDI Information
    attr_accessor :edi_invoice_extra2

    # Our electronic reference for EDI
    attr_accessor :edi_our_electronic_reference

    # Your electronic reference for EDI
    attr_accessor :edi_your_electronic_reference

    # Attribute mapping from ruby-style variable name to JSON key.
    def self.attribute_map
      {
        :'edi_global_location_number' => :'EDIGlobalLocationNumber',
        :'edi_global_location_number_delivery' => :'EDIGlobalLocationNumberDelivery',
        :'edi_invoice_extra1' => :'EDIInvoiceExtra1',
        :'edi_invoice_extra2' => :'EDIInvoiceExtra2',
        :'edi_our_electronic_reference' => :'EDIOurElectronicReference',
        :'edi_your_electronic_reference' => :'EDIYourElectronicReference'
      }
    end

    # Attribute type mapping.
    def self.swagger_types
      {
        :'edi_global_location_number' => :'String',
        :'edi_global_location_number_delivery' => :'String',
        :'edi_invoice_extra1' => :'String',
        :'edi_invoice_extra2' => :'String',
        :'edi_our_electronic_reference' => :'String',
        :'edi_your_electronic_reference' => :'String'
      }
    end

    # Initializes the object
    # @param [Hash] attributes Model attributes in the form of hash
    def initialize(attributes = {})
      return unless attributes.is_a?(Hash)

      # convert string to symbol for hash key
      attributes = attributes.each_with_object({}) { |(k, v), h| h[k.to_sym] = v }

      if attributes.has_key?(:'EDIGlobalLocationNumber')
        self.edi_global_location_number = attributes[:'EDIGlobalLocationNumber']
      end

      if attributes.has_key?(:'EDIGlobalLocationNumberDelivery')
        self.edi_global_location_number_delivery = attributes[:'EDIGlobalLocationNumberDelivery']
      end

      if attributes.has_key?(:'EDIInvoiceExtra1')
        self.edi_invoice_extra1 = attributes[:'EDIInvoiceExtra1']
      end

      if attributes.has_key?(:'EDIInvoiceExtra2')
        self.edi_invoice_extra2 = attributes[:'EDIInvoiceExtra2']
      end

      if attributes.has_key?(:'EDIOurElectronicReference')
        self.edi_our_electronic_reference = attributes[:'EDIOurElectronicReference']
      end

      if attributes.has_key?(:'EDIYourElectronicReference')
        self.edi_your_electronic_reference = attributes[:'EDIYourElectronicReference']
      end
    end

    # Show invalid properties with the reasons. Usually used together with valid?
    # @return Array for valid properties with the reasons
    def list_invalid_properties
      invalid_properties = Array.new
      invalid_properties
    end

    # Check to see if the all the properties in the model are valid
    # @return true if the model is valid
    def valid?
      true
    end

    # Checks equality by comparing each attribute.
    # @param [Object] Object to be compared
    def ==(o)
      return true if self.equal?(o)
      self.class == o.class &&
          edi_global_location_number == o.edi_global_location_number &&
          edi_global_location_number_delivery == o.edi_global_location_number_delivery &&
          edi_invoice_extra1 == o.edi_invoice_extra1 &&
          edi_invoice_extra2 == o.edi_invoice_extra2 &&
          edi_our_electronic_reference == o.edi_our_electronic_reference &&
          edi_your_electronic_reference == o.edi_your_electronic_reference
    end

    # @see the `==` method
    # @param [Object] Object to be compared
    def eql?(o)
      self == o
    end

    # Calculates hash code according to all attributes.
    # @return [Fixnum] Hash code
    def hash
      [edi_global_location_number, edi_global_location_number_delivery, edi_invoice_extra1, edi_invoice_extra2, edi_our_electronic_reference, edi_your_electronic_reference].hash
    end

    # Builds the object from hash
    # @param [Hash] attributes Model attributes in the form of hash
    # @return [Object] Returns the model itself
    def build_from_hash(attributes)
      return nil unless attributes.is_a?(Hash)
      self.class.swagger_types.each_pair do |key, type|
        if type =~ /\AArray<(.*)>/i
          # check to ensure the input is an array given that the attribute
          # is documented as an array but the input is not
          if attributes[self.class.attribute_map[key]].is_a?(Array)
            self.send("#{key}=", attributes[self.class.attribute_map[key]].map { |v| _deserialize($1, v) })
          end
        elsif !attributes[self.class.attribute_map[key]].nil?
          self.send("#{key}=", _deserialize(type, attributes[self.class.attribute_map[key]]))
        end # or else data not found in attributes(hash), not an issue as the data can be optional
      end

      self
    end

    # Deserializes the data based on type
    # @param string type Data type
    # @param string value Value to be deserialized
    # @return [Object] Deserialized data
    def _deserialize(type, value)
      case type.to_sym
      when :DateTime
        DateTime.parse(value)
      when :Date
        Date.parse(value)
      when :String
        value.to_s
      when :Integer
        value.to_i
      when :Float
        value.to_f
      when :BOOLEAN
        if value.to_s =~ /\A(true|t|yes|y|1)\z/i
          true
        else
          false
        end
      when :Object
        # generic object (usually a Hash), return directly
        value
      when /\AArray<(?<inner_type>.+)>\z/
        inner_type = Regexp.last_match[:inner_type]
        value.map { |v| _deserialize(inner_type, v) }
      when /\AHash<(?<k_type>.+?), (?<v_type>.+)>\z/
        k_type = Regexp.last_match[:k_type]
        v_type = Regexp.last_match[:v_type]
        {}.tap do |hash|
          value.each do |k, v|
            hash[_deserialize(k_type, k)] = _deserialize(v_type, v)
          end
        end
      else # model
        temp_model = StandoutFortnox.const_get(type).new
        temp_model.build_from_hash(value)
      end
    end

    # Returns the string representation of the object
    # @return [String] String presentation of the object
    def to_s
      to_hash.to_s
    end

    # to_body is an alias to to_hash (backward compatibility)
    # @return [Hash] Returns the object in the form of hash
    def to_body
      to_hash
    end

    # Returns the object in the form of hash
    # @return [Hash] Returns the object in the form of hash
    def to_hash
      hash = {}
      self.class.attribute_map.each_pair do |attr, param|
        value = self.send(attr)
        next if value.nil?
        hash[param] = _to_hash(value)
      end
      hash
    end

    # Outputs non-array value in the form of hash
    # For object, use to_hash. Otherwise, just return the value
    # @param [Object] value Any valid value
    # @return [Hash] Returns the value in the form of hash
    def _to_hash(value)
      if value.is_a?(Array)
        value.compact.map { |v| _to_hash(v) }
      elsif value.is_a?(Hash)
        {}.tap do |hash|
          value.each { |k, v| hash[k] = _to_hash(v) }
        end
      elsif value.respond_to? :to_hash
        value.to_hash
      else
        value
      end
    end

  end
end
